version: '3'
services:
  conjur-server:
    image: registry2.itci.conjur.net/conjur-appliance:5.16.17
    environment:
      CONJUR_AUTHENTICATORS: authn-iam/prod
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    hostname: conjur
    ports:
      - "443"


